image: rust:latest

stages:
  - test

pageboy-tests:
  stage: test
  script:
    - cargo check --features sync
    - cargo test --features sync --test test_sync
    - cargo test --features sync --lib
    - cargo check --features async_tokio
    - cargo test --features async_tokio --test test_async_tokio
    - cargo test --features async_tokio --lib
    - cargo check --features async_std
    - cargo test --features async_std --test test_async_std
    - cargo test --features async_std --lib
    - cargo check --features async_smol
    - cargo test --features async_smol --test test_async_smol
    - cargo test --features async_smol --lib
    - cargo test --bin openapi_from_code
