image: rust:latest

stages:
  - test
  - release

test:
  stage: test
  script:
    - sh ci/test.sh
  rules:
    - if: '$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH'

release:
  stage: release
  script:
    - sh ci/release.sh
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
